<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>LittleAges.Headless.Tests</AssemblyName>
    <RootNamespace>LittleAges.Headless.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\src\LittleAges.Headless\LittleAges.Headless.csproj" />
  </ItemGroup>
</Project>
